server:
  port: 8082

spring:
  application:
    name: review-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/aw_review?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ''

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    instanceId: ${random.value}

management:
  endpoints:
    web:
      exposure:
        include: 'info' #health

info:
  app:
    name: API de avaliações de produtos

logging:
  level:
    com.netflix.discovery.DiscoveryClient: DEBUG