server:
  port: 8082

spring:
  application:
    name: review-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/aw_review?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ''

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${random.value}
    hostname: review-api.awlocal