eureka:
  client:
    registerWithEureka: false # Deve se registrar ou não
    fetchRegistry: false # Deve buscar os registros ou não
  server:
    renewalPercentThreshold: 0.55 #Padrao 0.85 Evitar emergency
server:
  port: 8761 # Porta do Tomcat
