spring:
  application:
    name: service-registry-eureka
  security:
    user:
      name: eureka
      password: password123
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:password123@discovery1:8761/eureka/,http://eureka:password123@discovery2:8762/eureka/,http://eureka:password123@discovery3:8763/eureka/
  server:
    renewalPercentThreshold: 0.55
management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    health:
      enabled: true
      show-details: always

info:
  app:
    name: Servidor de descoberta

# Fim da configuração global
---
spring:
  config:
    activate:
      on-profile: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1 # importante para funcionamento do replica, caso contrário nao localiza
    instanceId: ${spring.application.name}:discovery1

---
spring:
  config:
    activate:
      on-profile: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
    instanceId: ${spring.application.name}:discovery2

---
spring:
  config:
    activate:
      on-profile: discovery3
server:
  port: 8763
eureka:
  instance:
    hostname: discovery3
    instanceId: ${spring.application.name}:discovery3